### PR TITLE
v5.4.0

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #51 
Closes #53

### CODE REVIEW

**Comment by BastianZim** [comment]
@jakirkham @msarahan would you mind having a look at this one and merging it? Would unblock some stuff downstream. 
Thank you!

**Comment by BastianZim** [comment]
Might also help #52

**Comment by beckermr** [comment]
@BastianZim would you like to add yourself as a maintainer here?

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
Thank you!

**Comment by BastianZim** [comment]
Thanks as well!

**Pull request merged**
