### PR TITLE
Re-render and other various minor fixes (lint, etc.)

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/auditwheel-feedstock/issues/2

* Combines the `skip` statements
* Fix selectors to have correct format
* Adds `build/number` and sets it to `0`
* Re-renders with `conda-smithy` 0.10.3

### CODE REVIEW

**Comment by jakirkham** [comment]
@msarahan, would you please take a look at this and let me know if it looks ok to you as soon as you have a chance?

**Comment by ericdill** [comment]
LGTM

**Comment by pelson** [comment]
I'm going to save @msarahan the cycle and merge. LGTM

**Comment by jakirkham** [comment]
Sounds good to me.

**Pull request merged**
